Traceback (most recent call last):
  File "C:\Users\jhc23\AppData\Local\Programs\Python\Python312\Lib\site-packages\myst_nb\core\execute\inline.py", line 128, in code_cell_outputs
    self._client.execute_cell(
  File "C:\Users\jhc23\AppData\Roaming\Python\Python312\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jhc23\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 686, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\jhc23\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\jhc23\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
5*amp+10*volt
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mDimensionMismatchError[0m                    Traceback (most recent call last)
Cell [1;32mIn[7], line 1[0m
[1;32m----> 1[0m [38;5;241;43m5[39;49m[38;5;241;43m*[39;49m[43mamp[49m[38;5;241;43m+[39;49m[38;5;241;43m10[39;49m[38;5;241;43m*[39;49m[43mvolt[49m

File [1;32m~\AppData\Local\Programs\Python\Python312\Lib\site-packages\brian2\units\fundamentalunits.py:1193[0m, in [0;36mQuantity.__array_ufunc__[1;34m(self, uf, method, *inputs, **kwargs)[0m
[0;32m   1190[0m [38;5;28;01melif[39;00m uf[38;5;241m.[39m[38;5;18m__name__[39m [38;5;129;01min[39;00m UFUNCS_MATCHING_DIMENSIONS [38;5;241m+[39m UFUNCS_COMPARISONS:
[0;32m   1191[0m     [38;5;66;03m# Ok if dimension of arguments match (for reductions, they always do)[39;00m
[0;32m   1192[0m     [38;5;28;01mif[39;00m method [38;5;241m==[39m [38;5;124m"[39m[38;5;124m__call__[39m[38;5;124m"[39m:
[1;32m-> 1193[0m         [43mfail_for_dimension_mismatch[49m[43m([49m
[0;32m   1194[0m [43m            [49m[43minputs[49m[43m[[49m[38;5;241;43m0[39;49m[43m][49m[43m,[49m
[0;32m   1195[0m [43m            [49m[43minputs[49m[43m[[49m[38;5;241;43m1[39;49m[43m][49m[43m,[49m
[0;32m   1196[0m [43m            [49m[43merror_message[49m[38;5;241;43m=[39;49m[43m([49m
[0;32m   1197[0m [43m                [49m[38;5;124;43m"[39;49m[38;5;124;43mCannot calculate [39;49m[38;5;132;43;01m{val1}[39;49;00m[38;5;124;43m [39;49m[38;5;132;43;01m%s[39;49;00m[38;5;124;43m [39;49m[38;5;132;43;01m{val2}[39;49;00m[38;5;124;43m, the units do not match[39;49m[38;5;124;43m"[39;49m
[0;32m   1198[0m [43m            [49m[43m)[49m
[0;32m   1199[0m [43m            [49m[38;5;241;43m%[39;49m[43m [49m[43muf[49m[38;5;241;43m.[39;49m[38;5;18;43m__name__[39;49m[43m,[49m
[0;32m   1200[0m [43m            [49m[43mval1[49m[38;5;241;43m=[39;49m[43minputs[49m[43m[[49m[38;5;241;43m0[39;49m[43m][49m[43m,[49m
[0;32m   1201[0m [43m            [49m[43mval2[49m[38;5;241;43m=[39;49m[43minputs[49m[43m[[49m[38;5;241;43m1[39;49m[43m][49m[43m,[49m
[0;32m   1202[0m [43m        [49m[43m)[49m
[0;32m   1203[0m     [38;5;28;01mif[39;00m uf[38;5;241m.[39m[38;5;18m__name__[39m [38;5;129;01min[39;00m UFUNCS_COMPARISONS:
[0;32m   1204[0m         [38;5;28;01mreturn[39;00m uf_method([38;5;241m*[39m[np[38;5;241m.[39masarray(i) [38;5;28;01mfor[39;00m i [38;5;129;01min[39;00m inputs], [38;5;241m*[39m[38;5;241m*[39mkwargs)

File [1;32m~\AppData\Local\Programs\Python\Python312\Lib\site-packages\brian2\units\fundamentalunits.py:266[0m, in [0;36mfail_for_dimension_mismatch[1;34m(obj1, obj2, error_message, **error_quantities)[0m
[0;32m    264[0m         [38;5;28;01mraise[39;00m DimensionMismatchError(error_message, dim1)
[0;32m    265[0m     [38;5;28;01melse[39;00m:
[1;32m--> 266[0m         [38;5;28;01mraise[39;00m DimensionMismatchError(error_message, dim1, dim2)
[0;32m    267[0m [38;5;28;01melse[39;00m:
[0;32m    268[0m     [38;5;28;01mreturn[39;00m dim1, dim2

[1;31mDimensionMismatchError[0m: Cannot calculate 5. A add 10. V, the units do not match (units are A and V).

